import { isForgeRepoConstitution, isFoundryDecisionLedgerReport } from "./foundryForgeInput.js";
import { forgeBulletList, safeForgeList, safeForgeScore, safeForgeSummary, safeForgeText, shortForgeReason } from "./foundryForgeSafety.js";
import type { FoundryDecisionLedgerEntry, FoundryDecisionLedgerReport, FoundryDecisionRoute } from "./foundryDecisionLedgerTypes.js";
import type {
  FoundryForgePreview,
  FoundryForgePreviewInput,
  FoundryForgePreviewKind,
  FoundryForgePreviewReport,
  FoundryForgeSection
} from "./foundryForgeTypes.js";
import type { PullRequestTemplateSummary, RecentPullRequestStyleSummary, RepoConstitution, RepoConstitutionFinding } from "./repoConstitutionTypes.js";

export type { FoundryForgePreviewInput, FoundryForgePreviewReport } from "./foundryForgeTypes.js";

const DISCLAIMER = "Generated by architect-mcp Foundry Mode as an approval-required preview: https://github.com/tonycdr-prog/architect-mcp";
const FALLBACK_PR_HEADINGS = ["Summary", "Verification", "Release notes"];
const MAX_HEADINGS = 8;

export function forgeFoundryPreviews(input: FoundryForgePreviewInput = {}): FoundryForgePreviewReport {
  const ledger = isFoundryDecisionLedgerReport(input.ledger) ? input.ledger : emptyLedger();
  const constitution = isForgeRepoConstitution(input.repoConstitution) ? input.repoConstitution : undefined;
  const previews = ledger.entries.map((entry, index) => previewFor(entry, index, constitution));
  return {
    schemaVersion: 1,
    summary: summarizePreviews(ledger.entries.length, previews),
    previews,
    publicSafety: {
      rawPayloadsIncluded: false,
      rawRepoContentIncluded: false,
      localPathsIncluded: false,
      tokenValuesIncluded: false,
      mutationAllowed: false,
      publicPreviewsOnly: true
    }
  };
}

function previewFor(entry: FoundryDecisionLedgerEntry, index: number, constitution: RepoConstitution | undefined): FoundryForgePreview {
  const kind = kindFor(entry.route);
  const verificationPlan = safeForgeList(entry.verificationRequirements.length > 0 ? entry.verificationRequirements : ["Record a passing verification check before mutation approval."]);
  const releaseNoteImpact = releaseNoteImpactFor(entry);
  const warnings = warningsFor(entry, constitution);
  const maintainerFitRationale = maintainerFitRationaleFor(kind, constitution);
  const sections = kind === "pull_request"
    ? pullRequestSections(entry, constitution, verificationPlan, releaseNoteImpact)
    : nonPullRequestSections(entry, kind, verificationPlan, releaseNoteImpact);
  return {
    id: `ffp-${String(index + 1).padStart(3, "0")}-${kind}`,
    kind,
    route: entry.route,
    sourceDecisionId: safeForgeText(entry.id),
    evidenceIds: entry.evidenceIds.map(safeForgeText),
    title: titleFor(entry, kind),
    body: bodyFor(sections, warnings),
    sections,
    verificationPlan,
    releaseNoteImpact,
    maintainerFitRationale,
    disclaimer: DISCLAIMER,
    warnings,
    mutation: {
      serverMutationAllowed: false,
      explicitApprovalRequired: entry.mutation.explicitApprovalRequired || entry.approvalState !== "not_required"
    }
  };
}

function kindFor(route: FoundryDecisionRoute): FoundryForgePreviewKind {
  if (route === "pr_preview") return "pull_request";
  if (route === "architect_issue") return "architect_issue";
  if (route === "exception") return "exception_record";
  if (route === "no_op") return "no_op_record";
  return "human_question";
}

function pullRequestSections(
  entry: FoundryDecisionLedgerEntry,
  constitution: RepoConstitution | undefined,
  verificationPlan: string[],
  releaseNoteImpact: string
): FoundryForgeSection[] {
  const headings = prHeadingsFor(constitution);
  return headings.map((heading) => ({
    heading,
    content: contentForHeading(heading, entry, verificationPlan, releaseNoteImpact)
  }));
}

function nonPullRequestSections(
  entry: FoundryDecisionLedgerEntry,
  kind: FoundryForgePreviewKind,
  verificationPlan: string[],
  releaseNoteImpact: string
): FoundryForgeSection[] {
  if (kind === "architect_issue") {
    return [
      { heading: "Summary", content: summaryContent(entry) },
      { heading: "Evidence", content: evidenceContent(entry) },
      { heading: "Verification", content: forgeBulletList(verificationPlan) },
      { heading: "Mutation boundary", content: "Preview only. Do not create this issue without explicit maintainer approval." }
    ];
  }
  if (kind === "exception_record") {
    return [
      { heading: "Exception candidate", content: summaryContent(entry) },
      { heading: "Evidence", content: evidenceContent(entry) },
      { heading: "Verification", content: forgeBulletList(verificationPlan) },
      { heading: "Release notes", content: releaseNoteImpact }
    ];
  }
  if (kind === "no_op_record") {
    return [
      { heading: "No-op rationale", content: summaryContent(entry) },
      { heading: "Evidence", content: evidenceContent(entry) }
    ];
  }
  return [
    { heading: "Question", content: summaryContent(entry) },
    { heading: "Evidence", content: evidenceContent(entry) },
    { heading: "Verification", content: forgeBulletList(verificationPlan) },
    { heading: "Mutation boundary", content: "Human review is required before any PR, issue, exception, or repository mutation." }
  ];
}

function prHeadingsFor(constitution: RepoConstitution | undefined): string[] {
  if (!constitution) return FALLBACK_PR_HEADINGS;
  const usableTemplateHeadings = uniqueHeadings(constitution.pullRequests.templates
    .filter((template) => template.contentProvided && !template.hiddenCommentOnly && template.headings.length > 0)
    .flatMap((template) => template.headings));
  const requiredHeadings = requiredTemplateHeadings(constitution.pullRequests.templates);
  if (usableTemplateHeadings.length > 0) return uniqueHeadings([...usableTemplateHeadings, ...requiredHeadings]).slice(0, MAX_HEADINGS);

  const recentHeadings = uniqueHeadings(constitution.pullRequests.recentStyle.commonHeadings.map((item) => item.heading));
  if (recentHeadings.length > 0) return uniqueHeadings([...recentHeadings, ...requiredHeadings]).slice(0, MAX_HEADINGS);
  return uniqueHeadings([...FALLBACK_PR_HEADINGS, ...requiredHeadings]).slice(0, MAX_HEADINGS);
}

function requiredTemplateHeadings(templates: PullRequestTemplateSummary[]): string[] {
  const required: string[] = [];
  if (templates.some((template) => template.mentionsLinkedIssues)) required.push("Linked issues");
  if (templates.some((template) => template.mentionsVerification)) required.push("Verification");
  if (templates.some((template) => template.mentionsReleaseNotes)) required.push("Release notes");
  return required;
}

function contentForHeading(heading: string, entry: FoundryDecisionLedgerEntry, verificationPlan: string[], releaseNoteImpact: string): string {
  const normalized = normalizeHeading(heading);
  if (/summary|description|what|change|overview/.test(normalized)) return summaryContent(entry);
  if (/why|rationale|context/.test(normalized)) return safeForgeSummary(entry.decisionReason);
  if (/test|verification|validation|check/.test(normalized)) return forgeBulletList(verificationPlan);
  if (/release|changelog|note/.test(normalized)) return releaseNoteImpact;
  if (/issue|ticket|link/.test(normalized)) return "No external issue is linked by this preview unless a maintainer approves one.";
  if (/risk|impact/.test(normalized)) return "Mutation risk is not claimed by this preview; review the diff and verification plan before approval.";
  return "No repo-specific facts were inferred for this section. Fill this in only after maintainer review.";
}

function summaryContent(entry: FoundryDecisionLedgerEntry): string {
  return [
    safeForgeSummary(entry.decisionReason),
    evidenceContent(entry),
    "This is a preview only and does not imply mutation approval."
  ].join("\n\n");
}

function evidenceContent(entry: FoundryDecisionLedgerEntry): string {
  const evidence = entry.evidenceIds.length > 0 ? entry.evidenceIds.map(safeForgeText).join(", ") : "none supplied";
  return `Foundry route: ${entry.route}. Ledger evidence aliases: ${evidence}. Score: ${safeForgeScore(entry.source.score)}.`;
}

function releaseNoteImpactFor(entry: FoundryDecisionLedgerEntry): string {
  const joined = `${entry.decisionReason} ${entry.verificationRequirements.join(" ")}`.toLowerCase();
  if (/release|changelog|version|publish|package|workflow/.test(joined)) {
    return "Release-note impact is possible; maintainer must decide before mutation approval.";
  }
  return "No release-note impact is claimed by this preview; maintainer must confirm before mutation approval.";
}

function maintainerFitRationaleFor(kind: FoundryForgePreviewKind, constitution: RepoConstitution | undefined): string {
  if (kind !== "pull_request") return "This preview is routed from the decision ledger rather than inferred maintainer preference.";
  if (!constitution) return "No repo constitution was supplied, so the preview uses a conservative fallback PR structure.";
  if (hasFinding(constitution.findings, "RECENT_PR_STYLE_DIVERGES")) {
    return "Repository template headings are preserved as hard signals; recent accepted PR headings are advisory because they diverge from the template.";
  }
  if (constitution.pullRequests.templates.some((template) => template.contentProvided && !template.hiddenCommentOnly && template.headings.length > 0)) {
    return "Repository PR template headings are used as hard maintainer signals.";
  }
  if (constitution.pullRequests.recentStyle.commonHeadings.length > 0) {
    return "Recent accepted PR headings are used as advisory fallback because no usable template headings were supplied.";
  }
  return "No usable template or recent PR style was supplied, so the preview uses conservative default headings.";
}

function warningsFor(entry: FoundryDecisionLedgerEntry, constitution: RepoConstitution | undefined): string[] {
  const warnings: string[] = [];
  if (entry.redactionState !== "public") warnings.push("Decision ledger entry is redacted or sensitive; keep this preview internal until disclosure is approved.");
  if (!constitution) warnings.push("No repo constitution was supplied; PR template and recent maintainer style could not be applied.");
  if (constitution) {
    if (hasFinding(constitution.findings, "MISSING_PR_TEMPLATE")) warnings.push("No PR template was found; recent accepted PR style is advisory only.");
    if (hasFinding(constitution.findings, "HIDDEN_OR_SPARSE_PR_TEMPLATE")) warnings.push("PR template is hidden-comment-only or sparse; preserve hidden requirements and use recent style only as advisory.");
    if (hasFinding(constitution.findings, "RECENT_PR_STYLE_DIVERGES")) warnings.push("Recent accepted PR style diverges from the template; preserve template headings first.");
    if (constitution.ci.workflows.length === 0) warnings.push("No CI workflow was found; verification commands must be confirmed before mutation approval.");
  }
  return safeForgeList(warnings);
}

function titleFor(entry: FoundryDecisionLedgerEntry, kind: FoundryForgePreviewKind): string {
  const prefixes: Record<FoundryForgePreviewKind, string> = {
    pull_request: "[foundry-preview]",
    architect_issue: "[foundry-issue]",
    exception_record: "[foundry-exception]",
    no_op_record: "[foundry-no-op]",
    human_question: "[foundry-question]"
  };
  return `${prefixes[kind]} ${shortForgeReason(entry.decisionReason)}`;
}

function bodyFor(sections: FoundryForgeSection[], warnings: string[]): string {
  const renderedSections = sections.map((section) => `## ${safeForgeText(section.heading)}\n\n${safeForgeSummary(section.content)}`);
  const warningSection = warnings.length > 0 ? [`## Warnings\n\n${forgeBulletList(warnings)}`] : [];
  return [...renderedSections, ...warningSection, `---\n${DISCLAIMER}`].join("\n\n");
}

function summarizePreviews(totalDecisions: number, previews: FoundryForgePreview[]): FoundryForgePreviewReport["summary"] {
  return {
    totalDecisions,
    previewsGenerated: previews.length,
    pullRequestPreviews: previews.filter((preview) => preview.kind === "pull_request").length,
    architectIssuePreviews: previews.filter((preview) => preview.kind === "architect_issue").length,
    exceptionRecords: previews.filter((preview) => preview.kind === "exception_record").length,
    noOpRecords: previews.filter((preview) => preview.kind === "no_op_record").length,
    humanQuestions: previews.filter((preview) => preview.kind === "human_question").length,
    skipped: totalDecisions - previews.length,
    serverWritesPerformed: 0
  };
}

function hasFinding(findings: RepoConstitutionFinding[], code: RepoConstitutionFinding["code"]): boolean {
  return findings.some((finding) => finding.code === code);
}

function uniqueHeadings(values: string[]): string[] {
  const seen = new Set<string>();
  const headings: string[] = [];
  for (const value of values) {
    const heading = safeForgeText(value);
    const key = normalizeHeading(heading);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    headings.push(heading);
  }
  return headings;
}

function normalizeHeading(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

function emptyLedger(): FoundryDecisionLedgerReport {
  return {
    schemaVersion: 1,
    ledgerId: "foundry-ledger",
    summary: {
      totalEntries: 0,
      byRoute: {},
      approvalRequired: 0,
      humanRequired: 0,
      publicSafetyHolds: 0,
      serverWritesPerformed: 0
    },
    entries: [],
    publicSafety: {
      rawPayloadsIncluded: false,
      rawRepoContentIncluded: false,
      localPathsIncluded: false,
      tokenValuesIncluded: false,
      mutationAllowed: false,
      publicLedgerOnly: true
    }
  };
}
