import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createArchitectServer } from "../src/server/createArchitectServer.js";

describe("Foundry forge preview MCP tool", () => {
  it("chains constitution, evidence, scoring, routing, and preview forging without mutation", async () => {
    const { client, close } = await connectTestClient();
    try {
      const constitution = await callJson(client, "derive_repo_constitution", {
        files: [
          { path: ".github/pull_request_template.md", lines: 7 },
          { path: ".github/workflows/ci.yml", lines: 3 },
          { path: "package.json", lines: 1 }
        ],
        artifacts: [
          { path: ".github/pull_request_template.md", content: "## Summary\n\n## Verification\n\n## Release notes\n" },
          { path: ".github/workflows/ci.yml", content: "name: CI\non:\n  pull_request:\n" },
          { path: "package.json", content: JSON.stringify({ name: "demo", scripts: { test: "node --test" } }) }
        ],
        recentPullRequests: [
          { number: 5, author: "maintainer", authorAssociation: "OWNER", merged: true, body: "## What changed\n\n## Test plan\n" }
        ]
      });
      const normalized = await callJson(client, "normalize_foundry_evidence", {
        findings: [{
          code: "ARCH008_ENV_SCATTER",
          confidence: "high",
          severity: "error",
          path: "src/config/env.ts",
          message: "Environment access is scattered.",
          recommendation: "Centralize environment parsing."
        }],
        verification: [{ check: "npm test", status: "passed" }],
        repoConstitution: constitution.constitution
      });
      const scored = await callJson(client, "score_foundry_actionability", {
        inventory: normalized.inventory
      });
      const routed = await callJson(client, "route_foundry_decisions", {
        actionability: scored.actionability
      });
      const forged = await callJson(client, "forge_foundry_previews", {
        ledger: routed.ledger,
        repoConstitution: constitution.constitution
      });
      const serialized = JSON.stringify(forged.forge);

      assert.equal(forged.forge.schemaVersion, 1);
      assert.equal(forged.forge.summary.serverWritesPerformed, 0);
      assert.equal(forged.forge.publicSafety.mutationAllowed, false);
      assert.equal(forged.forge.publicSafety.publicPreviewsOnly, true);
      assert.equal(forged.forge.previews.some((preview: { kind: string }) => preview.kind === "pull_request"), true);
      assert.match(serialized, /Generated by architect-mcp Foundry Mode/);
      assert.match(serialized, /## Verification/);
      assert.equal(serialized.includes("\"path\""), false);
      assert.equal(serialized.includes("src/config/env.ts"), false);
    } finally {
      await close();
    }
  });

  it("replays every route and redacts unsafe preview text", async () => {
    const { client, close } = await connectTestClient();
    try {
      const forge = await callJson(client, "forge_foundry_previews", {
        ledger: {
          schemaVersion: 1,
          ledgerId: "foundry-ledger",
          summary: {
            totalEntries: 5,
            byRoute: {},
            approvalRequired: 3,
            humanRequired: 1,
            publicSafetyHolds: 1,
            serverWritesPerformed: 0
          },
          entries: ["pr_preview", "architect_issue", "exception", "no_op", "ask_human"].map((route, index) => ({
            id: `fdl-${index + 1}-${route}`,
            route,
            evidenceIds: [`fde-${index + 1}`],
            source: { score: 70 + index },
            decisionReason: index === 1 ? "Route architect_issue at score 71. payload: /Users/alice/project" : `Route ${route} at score ${70 + index}. Preview this safely.`,
            redactionState: index === 4 ? "sensitive" : "public",
            verificationRequirements: index === 2 ? ["Re-run ghp_abcdefghijklmnopqrstuvwxyz1234567890 before approval."] : ["Re-run npm test before approval."],
            approvalState: route === "ask_human" ? "human_required" : route === "no_op" ? "not_required" : "approval_required",
            nextAction: "Preview only.",
            mutation: { serverMutationAllowed: false, explicitApprovalRequired: route !== "no_op" }
          })),
          publicSafety: {
            rawPayloadsIncluded: false,
            rawRepoContentIncluded: false,
            localPathsIncluded: false,
            tokenValuesIncluded: false,
            mutationAllowed: false,
            publicLedgerOnly: true
          }
        }
      });
      const serialized = JSON.stringify(forge.forge);

      assert.deepEqual({
        pullRequestPreviews: forge.forge.summary.pullRequestPreviews,
        architectIssuePreviews: forge.forge.summary.architectIssuePreviews,
        exceptionRecords: forge.forge.summary.exceptionRecords,
        noOpRecords: forge.forge.summary.noOpRecords,
        humanQuestions: forge.forge.summary.humanQuestions
      }, {
        pullRequestPreviews: 1,
        architectIssuePreviews: 1,
        exceptionRecords: 1,
        noOpRecords: 1,
        humanQuestions: 1
      });
      assert.equal(serialized.includes("/Users/alice"), false);
      assert.equal(serialized.includes("ghp_abcdefghijklmnopqrstuvwxyz1234567890"), false);
      assert.equal(serialized.includes("payload:"), false);
      assert.equal(forge.forge.previews.every((preview: { mutation: { serverMutationAllowed: boolean } }) => preview.mutation.serverMutationAllowed === false), true);
    } finally {
      await close();
    }
  });
});

async function connectTestClient() {
  const server = createArchitectServer({ enableLocalWorkspaceTool: true, toolSurface: "advanced" });
  const client = new Client({ name: "architect-mcp-foundry-forge-test-client", version: "0.1.0" });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await Promise.all([
    client.connect(clientTransport),
    server.connect(serverTransport)
  ]);
  return {
    client,
    close: async () => {
      await client.close();
      await server.close();
    }
  };
}

async function callJson(client: Client, name: string, args: Record<string, unknown>) {
  const result = await client.callTool({ name, arguments: args });
  const text = result.content.find((content) => content.type === "text")?.text;
  assert.equal(typeof text, "string");
  return JSON.parse(text as string);
}
