import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { forgeFoundryPreviews } from "../src/domain/foundryForge.js";
import { deriveRepoConstitution } from "../src/domain/repoConstitution.js";
import type { FoundryDecisionLedgerEntry, FoundryDecisionLedgerReport } from "../src/domain/foundryDecisionLedgerTypes.js";

describe("forgeFoundryPreviews", () => {
  it("generates preview-only pull request bodies from repo template sections", () => {
    const constitution = deriveRepoConstitution({
      files: [
        { path: ".github/pull_request_template.md", lines: 7 },
        { path: ".github/workflows/ci.yml", lines: 3 },
        { path: "package.json", lines: 1 }
      ],
      artifacts: [
        { path: ".github/pull_request_template.md", content: "## Summary\n\n## Linked issues\n\n## Verification\n\n## Release notes\n" },
        { path: ".github/workflows/ci.yml", content: "name: CI\non:\n  pull_request:\n" },
        { path: "package.json", content: JSON.stringify({ name: "demo", scripts: { test: "node --test" } }) }
      ]
    });
    const forge = forgeFoundryPreviews({
      ledger: ledger([entry("pr_preview", { verificationRequirements: ["Re-run npm test before mutation approval."] })]),
      repoConstitution: constitution
    });

    assert.equal(forge.summary.pullRequestPreviews, 1);
    assert.equal(forge.summary.serverWritesPerformed, 0);
    assert.equal(forge.publicSafety.mutationAllowed, false);
    assert.deepEqual(forge.previews[0].sections.map((section) => section.heading), ["Summary", "Linked issues", "Verification", "Release notes"]);
    assert.match(forge.previews[0].body, /## Linked issues/);
    assert.match(forge.previews[0].body, /Re-run npm test before mutation approval/);
    assert.match(forge.previews[0].body, /Generated by architect-mcp Foundry Mode/);
    assert.equal(forge.previews[0].mutation.serverMutationAllowed, false);
  });

  it("preserves stale template headings while warning that recent PR style is advisory", () => {
    const constitution = deriveRepoConstitution({
      files: [
        { path: ".github/pull_request_template.md", lines: 3 },
        { path: ".github/workflows/ci.yml", lines: 3 }
      ],
      artifacts: [
        { path: ".github/pull_request_template.md", content: "## Summary\n\n## Verification\n" },
        { path: ".github/workflows/ci.yml", content: "name: CI\non: pull_request\n" }
      ],
      recentPullRequests: [
        { number: 7, author: "maintainer", authorAssociation: "OWNER", merged: true, body: "## What changed\n\n## Test plan\n" }
      ]
    });
    const forge = forgeFoundryPreviews({
      ledger: ledger([entry("pr_preview")]),
      repoConstitution: constitution
    });

    assert.deepEqual(forge.previews[0].sections.map((section) => section.heading), ["Summary", "Verification"]);
    assert.match(forge.previews[0].maintainerFitRationale, /template headings are preserved/);
    assert.equal(forge.previews[0].warnings.some((warning) => /Recent accepted PR style diverges/.test(warning)), true);
    assert.equal(forge.previews[0].body.includes("## What changed"), false);
  });

  it("uses recent accepted PR headings when templates are missing", () => {
    const constitution = deriveRepoConstitution({
      files: [{ path: ".github/workflows/ci.yml", lines: 1 }],
      artifacts: [{ path: ".github/workflows/ci.yml", content: "name: CI\non: pull_request\n" }],
      recentPullRequests: [
        { number: 11, author: "maintainer", authorAssociation: "MEMBER", merged: true, body: "## Motivation\n\n## Test plan\n" }
      ]
    });
    const forge = forgeFoundryPreviews({
      ledger: ledger([entry("pr_preview")]),
      repoConstitution: constitution
    });

    assert.deepEqual(forge.previews[0].sections.map((section) => section.heading), ["Motivation", "Test plan"]);
    assert.match(forge.previews[0].maintainerFitRationale, /advisory fallback/);
    assert.equal(forge.previews[0].warnings.some((warning) => /No PR template/.test(warning)), true);
  });

  it("accepts schema-compatible partial constitution flags without dropping template headings", () => {
    const forge = forgeFoundryPreviews({
      ledger: ledger([entry("pr_preview")]),
      repoConstitution: {
        schemaVersion: 1,
        pullRequests: {
          templates: [{
            path: ".github/pull_request_template.md",
            contentProvided: true,
            headings: ["Summary", "Verification"],
            checklistItems: 0
          }]
        },
        findings: []
      }
    });

    assert.deepEqual(forge.previews[0].sections.map((section) => section.heading), ["Summary", "Verification"]);
    assert.equal(forge.previews[0].warnings.some((warning) => /No repo constitution/.test(warning)), false);
    assert.equal(forge.previews[0].warnings.some((warning) => /No CI workflow/.test(warning)), true);
  });

  it("dedupes multiple template styles and generates architect issue previews safely", () => {
    const constitution = deriveRepoConstitution({
      files: [
        { path: ".github/PULL_REQUEST_TEMPLATE/bug.md", lines: 4 },
        { path: ".github/PULL_REQUEST_TEMPLATE/feature.md", lines: 4 },
        { path: ".github/workflows/ci.yml", lines: 3 }
      ],
      artifacts: [
        { path: ".github/PULL_REQUEST_TEMPLATE/bug.md", content: "## Summary\n\n## Test plan\n" },
        { path: ".github/PULL_REQUEST_TEMPLATE/feature.md", content: "## Summary\n\n## Release notes\n" },
        { path: ".github/workflows/ci.yml", content: "name: CI\non:\n  pull_request:\n" }
      ]
    });
    const forge = forgeFoundryPreviews({
      ledger: ledger([
        entry("pr_preview"),
        entry("architect_issue", {
          decisionReason: "Route architect_issue at score 67. stdout: /Users/alice/project secret",
          verificationRequirements: ["Re-run npm_abcdefghijklmnopqrstuvwxyz1234567890 before mutation approval."]
        })
      ]),
      repoConstitution: constitution
    });
    const serialized = JSON.stringify(forge);

    assert.deepEqual(forge.previews[0].sections.map((section) => section.heading), ["Summary", "Test plan", "Release notes", "Verification"]);
    assert.equal(forge.summary.architectIssuePreviews, 1);
    assert.equal(forge.previews[1].kind, "architect_issue");
    assert.equal(serialized.includes("/Users/alice"), false);
    assert.equal(serialized.includes("npm_abcdefghijklmnopqrstuvwxyz1234567890"), false);
    assert.equal(serialized.includes("stdout:"), false);
  });

  it("redacts raw-output markers from headings, ids, and evidence aliases", () => {
    const constitution = deriveRepoConstitution({
      files: [{ path: ".github/pull_request_template.md", lines: 1 }],
      artifacts: [{ path: ".github/pull_request_template.md", content: "## stdout: maintainer detail\n" }]
    });
    const forge = forgeFoundryPreviews({
      ledger: ledger([entry("pr_preview", {
        id: "stdout: private decision id",
        evidenceIds: ["payload: private evidence alias"]
      })]),
      repoConstitution: constitution
    });
    const serialized = JSON.stringify(forge);

    assert.equal(serialized.includes("stdout:"), false);
    assert.equal(serialized.includes("payload:"), false);
    assert.equal(serialized.includes("private decision id"), false);
    assert.equal(serialized.includes("private evidence alias"), false);
    assert.match(serialized, /\[redacted-raw-output\]/);
  });

  it("emits exception, no-op, and human-question records without mutation", () => {
    const forge = forgeFoundryPreviews({
      ledger: ledger([
        entry("exception"),
        entry("no_op"),
        entry("ask_human", { redactionState: "sensitive", approvalState: "human_required" })
      ])
    });

    assert.equal(forge.summary.exceptionRecords, 1);
    assert.equal(forge.summary.noOpRecords, 1);
    assert.equal(forge.summary.humanQuestions, 1);
    assert.equal(forge.previews.every((preview) => preview.mutation.serverMutationAllowed === false), true);
    assert.equal(forge.previews.some((preview) => preview.warnings.some((warning) => /No repo constitution/.test(warning))), true);
  });
});

function ledger(entries: FoundryDecisionLedgerEntry[]): FoundryDecisionLedgerReport {
  return {
    schemaVersion: 1,
    ledgerId: "foundry-ledger",
    summary: {
      totalEntries: entries.length,
      byRoute: {},
      approvalRequired: entries.filter((item) => item.approvalState === "approval_required").length,
      humanRequired: entries.filter((item) => item.approvalState === "human_required").length,
      publicSafetyHolds: entries.filter((item) => item.redactionState !== "public").length,
      serverWritesPerformed: 0
    },
    entries,
    publicSafety: {
      rawPayloadsIncluded: false,
      rawRepoContentIncluded: false,
      localPathsIncluded: false,
      tokenValuesIncluded: false,
      mutationAllowed: false,
      publicLedgerOnly: true
    }
  };
}

function entry(route: FoundryDecisionLedgerEntry["route"], overrides: Partial<FoundryDecisionLedgerEntry> = {}): FoundryDecisionLedgerEntry {
  const approvalState = route === "ask_human" ? "human_required" : route === "no_op" ? "not_required" : "approval_required";
  return {
    id: `fdl-001-${route}`,
    route,
    evidenceIds: ["fde-001"],
    source: { score: 72 },
    decisionReason: `Route ${route} at score 72. Keep the proposed change small and verifiable.`,
    redactionState: "public",
    verificationRequirements: ["Record a passing repo verification check before mutation approval."],
    approvalState,
    nextAction: "Preview only.",
    mutation: {
      serverMutationAllowed: false,
      explicitApprovalRequired: approvalState !== "not_required"
    },
    ...overrides
  };
}
