use serde_json::{Value, json, to_string_pretty};

use crate::foundry::{RepoFoundryPlan, repo_target};
use crate::session::TuiSession;

pub(crate) fn artifact_content(plan: &RepoFoundryPlan, session: &TuiSession, path: &str) -> String {
    match path {
        "AGENTS.md" => agents_md(plan),
        "README.md" => readme_md(plan),
        "package.json" => package_json(plan),
        "tests/foundry-scaffold.test.mjs" => scaffold_test(),
        ".env.example" => {
            "# Commit-safe environment template.\n# Add real values in local .env files only.\n"
                .to_string()
        }
        "docs/architecture-contract.md" => gate_markdown(session, "create_pre_edit_contract"),
        "docs/build-plan.md" => build_plan_md(session),
        ".github/workflows/ci.yml" => ci_workflow(plan),
        ".github/ISSUE_TEMPLATE/bug_report.md" => issue_template(),
        ".github/pull_request_template.md" => pull_request_template(),
        "docs/data-boundary.md" => data_boundary_md(),
        _ => format!("# {}\n\nGenerated by architect-mcp foundry.\n", path),
    }
}

pub(crate) fn first_pr_body(plan: &RepoFoundryPlan, session: &TuiSession) -> String {
    let target = repo_target(plan.owner.as_deref(), &plan.repo_name);
    format!(
        "# {}\n\nTarget repo: `{target}`\n\n## Evidence\n- `grill_me`: {}\n- `create_pre_edit_contract`: {}\n- `review_build_plan`: {}\n- `review_proposed_file_plan`: {}\n\n## Verification Required\n{}\n\n## Remaining Gaps\n- Replace pending verification lines with actual command output before marking ready.\n",
        plan.first_pr.title,
        has_gate(session, "grill_me"),
        has_gate(session, "create_pre_edit_contract"),
        has_gate(session, "review_build_plan"),
        has_gate(session, "review_proposed_file_plan"),
        plan.verification
            .iter()
            .map(|check| format!("- `{check}`: pending"))
            .collect::<Vec<_>>()
            .join("\n")
    )
}

fn agents_md(plan: &RepoFoundryPlan) -> String {
    format!(
        "# AGENTS.md\n\nThis repo was bootstrapped through architect-mcp foundry.\n\n## Guardrails\n- Start with `grill_me` before implementation.\n- Keep generated app changes behind a pre-edit contract.\n- Run verification before final/session review.\n- Do not commit secrets or raw local MCP config values.\n\n## Verification\n{}\n",
        plan.verification
            .iter()
            .map(|check| format!("- `{check}`"))
            .collect::<Vec<_>>()
            .join("\n")
    )
}

fn readme_md(plan: &RepoFoundryPlan) -> String {
    format!(
        "# {}\n\nPrivate app repository generated through architect-mcp foundry.\n\n## Verification\n{}\n",
        plan.repo_name,
        plan.verification
            .iter()
            .map(|check| format!("- `{check}`"))
            .collect::<Vec<_>>()
            .join("\n")
    )
}

fn package_json(plan: &RepoFoundryPlan) -> String {
    to_string_pretty(&json!({
        "private": true,
        "name": plan.repo_name,
        "scripts": { "test": "node --test tests/*.test.mjs" }
    }))
    .unwrap_or_else(|_| "{}".to_string())
}

fn scaffold_test() -> String {
    "import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport { existsSync } from 'node:fs';\n\ntest('foundry scaffold contains guardrail artifacts', () => {\n  for (const path of ['AGENTS.md', 'README.md', '.env.example', 'docs/architecture-contract.md', 'docs/build-plan.md', '.github/workflows/ci.yml']) {\n    assert.equal(existsSync(path), true, `${path} should exist`);\n  }\n});\n".to_string()
}

fn gate_markdown(session: &TuiSession, gate: &str) -> String {
    let Some(value) = session.gates.get(gate) else {
        return format!("# {gate}\n\nGate output was not recorded.\n");
    };
    if let Some(markdown) = value
        .get("contract")
        .and_then(|contract| contract.get("markdown"))
        .and_then(Value::as_str)
    {
        return markdown.to_string();
    }
    format!(
        "# {gate}\n\n```json\n{}\n```\n",
        to_string_pretty(value).unwrap_or_else(|_| "{}".to_string())
    )
}

fn build_plan_md(session: &TuiSession) -> String {
    let plan = session
        .gates
        .get("grill_me")
        .and_then(|value| value.get("buildPlan"))
        .cloned()
        .unwrap_or(Value::Null);
    format!(
        "# Build Plan\n\n```json\n{}\n```\n",
        to_string_pretty(&plan).unwrap_or_else(|_| "null".to_string())
    )
}

fn ci_workflow(plan: &RepoFoundryPlan) -> String {
    let commands = executable_verification_commands(&plan.verification);
    let commands = if commands.is_empty() {
        "echo \"No executable verification commands configured; see PR checklist.\"".to_string()
    } else {
        commands.join("\n")
    };
    format!(
        "name: CI\n\non:\n  pull_request:\n  push:\n    branches: [main]\n\njobs:\n  verify:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v6\n      - name: Verify\n        run: |\n{}\n",
        indent(&commands, 10)
    )
}

fn executable_verification_commands(checks: &[String]) -> Vec<String> {
    checks
        .iter()
        .map(|check| check.trim())
        .filter(|check| is_executable_check(check))
        .map(ToString::to_string)
        .collect()
}

fn is_executable_check(check: &str) -> bool {
    matches!(
        check.split_whitespace().next(),
        Some(
            "npm"
                | "pnpm"
                | "yarn"
                | "bun"
                | "cargo"
                | "node"
                | "python"
                | "pytest"
                | "go"
                | "dotnet"
        )
    )
}

fn issue_template() -> String {
    "---\nname: Bug report\nabout: Report a reproducible problem\n---\n\n## What happened\n\n## Expected behavior\n\n## Verification\n\n## Environment\n".to_string()
}

fn pull_request_template() -> String {
    "## Summary\n\n## Work Gate Evidence\n- Grill:\n- Contract:\n- Plan review:\n- File-plan review:\n\n## Verification\n\n## Assumptions\n\n## Remaining Gaps\n".to_string()
}

fn data_boundary_md() -> String {
    "# Data Boundary\n\nDocument database ownership, migrations, server-only access, and rollback before implementation.\n".to_string()
}

fn has_gate(session: &TuiSession, gate: &str) -> &'static str {
    if session.gates.contains_key(gate) {
        "recorded"
    } else {
        "missing"
    }
}

fn indent(value: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    value
        .lines()
        .map(|line| format!("{prefix}{line}"))
        .collect::<Vec<_>>()
        .join("\n")
}
