pub mod acp;
pub mod adapter;
mod adapter_health;
mod adapter_probe_command;
mod adapter_pty;
mod adapter_review;
pub mod config;
mod config_template;
mod gate_calls;
mod headless;
mod headless_adapter;
mod headless_events;
mod headless_support;
pub mod interactive;
mod interactive_commands;
mod interactive_support;
mod interactive_update;
pub mod mcp;
mod mcp_client;
pub mod orchestrator;
pub mod session;
pub mod ui;

pub const APP_NAME: &str = "architect-mcp-tui";
