pub mod acp;
mod acp_state;
pub mod adapter;
mod adapter_health;
mod adapter_probe_command;
mod adapter_pty;
mod adapter_review;
mod approval;
pub mod arena;
mod brief;
#[cfg(test)]
mod brief_tests;
pub mod config;
mod config_template;
mod gate_calls;
mod headless;
mod headless_adapter;
mod headless_events;
mod headless_support;
pub mod interactive;
mod interactive_approval;
mod interactive_arena;
mod interactive_commands;
mod interactive_diff;
mod interactive_gate_flow;
mod interactive_support;
mod interactive_update;
pub mod mcp;
mod mcp_client;
pub mod orchestrator;
pub mod session;
#[cfg(test)]
mod session_tests;
pub mod smoke;
mod smoke_report;
mod smoke_types;
pub mod ui;
mod verification;

pub const APP_NAME: &str = "architect-mcp-tui";
